import { dummyLogo } from "../src/assets/images/images";
import { JobType } from "../src/pages/Jobs/JobsPage";

export const mockJobsData: JobType[] = [
    {
      id: "1",
      position: "Frontend Developer",
      postedAt: "2024-10-01",
      contract: "Full Time",
      location: "Remote",
      apply: "https://example.com/apply",
      description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers.",
      companyId: "1",
      company: {
        name: "Example Corp",
        logo: dummyLogo,
        logoBackground: "#ffffff",
        website: "https://example.com",
      },
    },
    {
      id: "2",
      position: "Backend Developer",
      postedAt: "2024-10-02",
      contract: "Part Time",
      location: "Kamembe",
      apply: "https://example.com/apply",
      description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers.",
      companyId: "2",
      company: {
        name: "Another Corp",
        logo: dummyLogo,
        logoBackground: "#333",
        website: "https://another.com",
      },
    },
    {
      id: "3",
      position: "Fullstack Developer",
      postedAt: "2024-10-09",
      contract: "Full Time",
      location: "Kigali - Hybride",
      apply: "https://example.com/apply",
      description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers.",
      companyId: "3",
      company: {
        name: "Yet Another Corp",
        logo: dummyLogo,
        logoBackground: "#666",
        website: "https://yetanother.com",
      },
    },
    {
      id: "4",
      position: "DevOps Engineer",
      postedAt: "2024-10-04",
      contract: "Full Time",
      location: "Kigali",
      apply: "https://example.com/apply",
      description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers.",
      companyId: "4",
        company: {
            name: "And Another Corp",
            logo: dummyLogo,
            logoBackground: "#999",
            website: "https://andanother.com",
        },
    },
    {
      id: "5",
      position: "Data Scientist",
      postedAt: "2024-10-05",
      contract: "Part Time",
      location: "Musanze",
      apply: "https://example.com/apply",
      description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers.",
      companyId: "5",
        company: {
            name: "One More Corp",
            logo: dummyLogo,
            logoBackground: "#CCC",
            website: "https://onemore.com",
        },
    },
    {
      id: "6",
      position: "Product Manager",
      postedAt: "2024-10-06",
      contract: "Full Time",
      location: "Kigali - Gikondo",
      apply: "https://example.com/apply",
      description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers.",
      companyId: "6",
        company: {
            name: "Last Corp",
            logo: dummyLogo,
            logoBackground: "#FFF",
            website: "https://last.com",
        },
    },
    {
      id: "7",
      position: "UI/UX Designer",
      postedAt: "2024-10-07",
      contract: "Full Time",
      location: "Remote",
      apply: "https://example.com/apply",
      description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers.",
      companyId: "7",
        company: {
            name: "Final Corp",
            logo: dummyLogo,
            logoBackground: "#000",
            website: "https://final.com",
        },
    },
    {
      id: "8",
      position: "QA Engineer",
      postedAt: "2024-10-08",
      contract: "Full Time",
      location: "Hybrid",
      apply: "https://example.com/apply",
      description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers.",
      companyId: "8",
        company: {
            name: "Ultimate Corp",
            logo: dummyLogo,
            logoBackground: "#333",
            website: "https://ultimate.com",
        },
    },
    {
      id: "9",
      position: "Security Engineer",
      postedAt: "2024-10-09",
      contract: "Full Time",
      location: "Hybrid",
      apply: "https://example.com/apply",
      description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers.",
      companyId: "9",
        company: {
            name: "Penultimate Corp",
            logo: dummyLogo,
            logoBackground: "#666",
            website: "https://penultimate.com",
        },
    },
    {
      id: "10",
      position: "Technical Writer",
      postedAt: "2024-10-10",
      contract: "Full Time",
      location: "Kigali",
      apply: "https://example.com/apply",
      description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers.",
        companyId: "10",
            company: {
                name: "Final Corp",
                logo: dummyLogo,
                logoBackground: "#999",
                website: "https://final.com",
            },
    },
    {
      id: "11",
      position: "UX/UI Designer",
      postedAt: "2024-10-11",
      contract: "Full Time",
      location: "Remote",
      apply: "https://example.com/apply",
      description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers.",
      companyId: "11",
        company: {
            name: "Ultimate Corp",
            logo: dummyLogo,
            logoBackground: "#CCC",
            website: "https://ultimate.com",
        },
    },
    {
      id: "12",
      position: "QA Engineer",
      postedAt: "2024-10-12",
      contract: "Full Time",
      location: "Remote",
      apply: "https://example.com/apply",
      description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers.",
      companyId: "12",
        company: {
            name: "Penultimate Corp",
            logo: dummyLogo,
            logoBackground: "#FFF",
            website: "https://penultimate.com",
        },
    },
    {
      id: "13",
      position: "Security Engineer",
      postedAt: "2024-10-13",
      contract: "Full Time",
      location: "Kamembe",
      apply: "https://example.com/apply",
      description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers.",
      companyId: "13",
        company: {
            name: "Final Corp",
            logo: dummyLogo,
            logoBackground: "#000",
            website: "https://final.com",
        },
    }
  ];
  