import { JobType } from "../src/components/Jobs/Jobs";

export const mockJobsData: JobType[] = [
    {
      id: "1",
      position: "Frontend Developer",
      postedAt: "2023-10-01",
      contract: "Full Time",
      location: "Remote",
      apply: "https://example.com/apply",
      description: "We are looking for a Frontend Developer...",
      companyId: "1",
      company: {
        name: "Example Corp",
        logo: "logo1.png",
        logoBackground: "#000",
        website: "https://example.com",
      },
    },
    {
      id: "2",
      position: "Backend Developer",
      postedAt: "2023-10-02",
      contract: "Part Time",
      location: "New York",
      apply: "https://example.com/apply",
      description: "We are looking for a Backend Developer...",
      companyId: "2",
      company: {
        name: "Another Corp",
        logo: "logo2.png",
        logoBackground: "#333",
        website: "https://another.com",
      },
    },
    {
      id: "3",
      position: "Fullstack Developer",
      postedAt: "2023-10-03",
      contract: "Full Time",
      location: "San Francisco",
      apply: "https://example.com/apply",
      description: "We are looking for a Fullstack Developer...",
      companyId: "3",
      company: {
        name: "Yet Another Corp",
        logo: "logo3.png",
        logoBackground: "#666",
        website: "https://yetanother.com",
      },
    },
    {
      id: "4",
      position: "DevOps Engineer",
      postedAt: "2023-10-04",
      contract: "Full Time",
      location: "Los Angeles",
      apply: "https://example.com/apply",
      description: "We are looking for a DevOps Engineer...",
      companyId: "4",
        company: {
            name: "And Another Corp",
            logo: "logo4.png",
            logoBackground: "#999",
            website: "https://andanother.com",
        },
    },
    {
      id: "5",
      position: "Data Scientist",
      postedAt: "2023-10-05",
      contract: "Part Time",
      location: "Chicago",
      apply: "https://example.com/apply",
      description: "We are looking for a Data Scientist...",
      companyId: "5",
        company: {
            name: "One More Corp",
            logo: "logo5.png",
            logoBackground: "#CCC",
            website: "https://onemore.com",
        },
    },
    {
      id: "6",
      position: "Product Manager",
      postedAt: "2023-10-06",
      contract: "Full Time",
      location: "Seattle",
      apply: "https://example.com/apply",
      description: "We are looking for a Product Manager...",
      companyId: "6",
        company: {
            name: "Last Corp",
            logo: "logo6.png",
            logoBackground: "#FFF",
            website: "https://last.com",
        },
    },
    {
      id: "7",
      position: "UI/UX Designer",
      postedAt: "2023-10-07",
      contract: "Full Time",
      location: "Portland",
      apply: "https://example.com/apply",
      description: "We are looking for a UI/UX Designer...",
      companyId: "7",
        company: {
            name: "Final Corp",
            logo: "logo7.png",
            logoBackground: "#000",
            website: "https://final.com",
        },
    },
    {
      id: "8",
      position: "QA Engineer",
      postedAt: "2023-10-08",
      contract: "Full Time",
      location: "Austin",
      apply: "https://example.com/apply",
      description: "We are looking for a QA Engineer...",
      companyId: "8",
        company: {
            name: "Ultimate Corp",
            logo: "logo8.png",
            logoBackground: "#333",
            website: "https://ultimate.com",
        },
    },
    {
      id: "9",
      position: "Security Engineer",
      postedAt: "2023-10-09",
      contract: "Full Time",
      location: "Miami",
      apply: "https://example.com/apply",
      description: "We are looking for a Security Engineer...",
      companyId: "9",
        company: {
            name: "Penultimate Corp",
            logo: "logo9.png",
            logoBackground: "#666",
            website: "https://penultimate.com",
        },
    },
    {
      id: "10",
      position: "Technical Writer",
      postedAt: "2023-10-10",
      contract: "Full Time",
      location: "Denver",
      apply: "https://example.com/apply",
      description: "We are looking for a",
        companyId: "10",
            company: {
                name: "Final Corp",
                logo: "logo10.png",
                logoBackground: "#999",
                website: "https://final.com",
            },
    },
  ];
  